### ISSUE TITLE
Can't connect to server, causes error

### ISSUE THREAD

**Issue by martinGITHUBER** [SkeldJS/SkeldJS#15]
I can't do `await client.connect('NA', 'meeee');` because that gives me an error:
```
throw new TypeError("Expected an integer, instead got a fraction.");
                  ^

TypeError: Expected an integer, instead got a fraction.
    at Function.checkInteger (/Users/hacker/Documents/GitHub/ConsoleAmogus/node_modules/@skeldjs/util/dist/lib/HazelBuffer.js:14:19)
    at HazelWriter.int32 (/Users/hacker/Documents/GitHub/ConsoleAmogus/node_modules/@skeldjs/util/dist/lib/HazelWriter.js:317:35)
    at VersionInfo.Serialize (/Users/hacker/Documents/GitHub/ConsoleAmogus/node_modules/@skeldjs/util/dist/lib/Version.js:35:16)
    at HazelWriter.write (/Users/hacker/Documents/GitHub/ConsoleAmogus/node_modules/@skeldjs/util/dist/lib/HazelWriter.js:211:22)
    at HelloPacket.Serialize (/Users/hacker/Documents/GitHub/ConsoleAmogus/node_modules/@skeldjs/protocol/dist/lib/packets/option/Hello.js:31:16)
    at HazelWriter.write (/Users/hacker/Documents/GitHub/ConsoleAmogus/node_modules/@skeldjs/util/dist/lib/HazelWriter.js:211:22)
    at SkeldjsClient.send (/Users/hacker/Documents/GitHub/ConsoleAmogus/node_modules/@skeldjs/client/dist/lib/client.js:183:20)
    at SkeldjsClient.identify (/Users/hacker/Documents/GitHub/ConsoleAmogus/node_modules/@skeldjs/client/dist/lib/client.js:153:20)
    at async SkeldjsClient.connect (/Users/hacker/Documents/GitHub/ConsoleAmogus/node_modules/@skeldjs/client/dist/lib/client.js:107:17)
    at async SkeldjsClient.connect (/Users/hacker/Documents/GitHub/ConsoleAmogus/node_modules/@skeldjs/client/dist/lib/client.js:93:20)
```

Here is my code:
```
const skeldjs = require('@skeldjs/client');

(async () => {
	const client = new skeldjs.SkeldjsClient(‎'2021.6.15');

	await client.connect('NA', 'meeee');
	console.info('Connected to server');
})();
```

**Comment by edqx** [comment]
I can't reproduce this, although for some reason node and visual studio code have a problem with your `(` and `'`.
![vsc-whats-going-on](https://user-images.githubusercontent.com/60631511/125160496-197d5700-e175-11eb-99e1-f328bca2be47.gif)

The client version should be set to `2021.6.30` too.

**Comment by martinGITHUBER** [comment]
Turns out it was because I copied and pasted the line with `new skeldjs.SkeldjsClient` from the website, which pasted some invalid unicode characters(As I saw when I used `diff` on the correct and incorrect .js files, which looked identical, but diff said that line was different). If I type out that line(and not copy paste), then it works like normal.
