### ISSUE TITLE
ConnectError: The Among Us servers could not authenticate you.

### ISSUE THREAD

**Issue by 0tv** [SkeldJS/SkeldJS#33]
i am using the following code:
```js
import skeldjs from "@skeldjs/client";
import util from "@skeldjs/util";
const { AuthMethod, EosHttpApi } = skeldjs;
const { GameCode } = util;

const clientId = "xyza7891qtrmoYLr86we6DlfCA1RRsp8";
const clientSecret = "nGThQanzvthA2HPaARXe/xutzsKyx5WJveNkBx44ti4";
const deploymentId = "3ce14d8292084c80a8364a8b5f0dfbf4";

const randomDeviceModel = EosHttpApi.generateRandomDeviceModel();

const { access_token } = await EosHttpApi.authRequestGetDeviceIdAccessToken(clientId, clientSecret, randomDeviceModel);

const account = await EosHttpApi.authRequestEosAccessToken({
    grantType: "external_auth",
    externalAuthType: "deviceid_access_token",
    clientId: clientId,
    clientSecret: clientSecret,
    deploymentId: deploymentId,
    nonce: "aaaaaaaaab",
    displayName: "lxwusr",
    externalAuthToken: access_token,
});

const client = new skeldjs.SkeldjsClient("2022.9.2.0s", "lxwusr", {
    authMethod: AuthMethod.SecureTransport,
    idToken: account.id_token,
    eosProductUserId: account.product_user_id
});

await client.connect("https://matchmaker-eu.among.us", 443);
const code = await client.createGame();

client.myPlayer?.control?.checkName("weakeyes");
client.myPlayer?.control?.checkColor(skeldjs.Color.Red);

console.log(code);
console.log("Created game @ %s", GameCode.convertIntToString(code));
```
however this results in the following error:
```
C:\Users\leaf\Desktop\skeldjs>node index.js
C:\Users\leaf\Desktop\skeldjs\node_modules\@skeldjs\client\dist\lib\client.js:257
                rej(new errors_1.ConnectError(ev.reason, ev.message || data_1.DisconnectMessages[ev.reason] || ""));
                    ^

ConnectError: The Among Us servers could not authenticate you.

You must have an Among Us account to play online. (Guest account is okay!)
    at Array.onDisconnect (C:\Users\leaf\Desktop\skeldjs\node_modules\@skeldjs\client\dist\lib\client.js:257:21)
    at SkeldjsClient.emitSync (C:\Users\leaf\Desktop\skeldjs\node_modules\@skeldjs\events\dist\lib\EventEmitter.js:27:25)
    at C:\Users\leaf\Desktop\skeldjs\node_modules\@skeldjs\client\dist\lib\client.js:72:18
    at PacketDecoder.emit (C:\Users\leaf\Desktop\skeldjs\node_modules\@skeldjs\protocol\dist\lib\PacketDecoder.js:83:31)
    at PacketDecoder.emitDecoded (C:\Users\leaf\Desktop\skeldjs\node_modules\@skeldjs\protocol\dist\lib\PacketDecoder.js:60:20)
    at SkeldjsClient.handleInboundMessage (C:\Users\leaf\Desktop\skeldjs\node_modules\@skeldjs\client\dist\lib\client.js:365:28)
    at DtlsSocket.emit (node:events:390:28)
    at DtlsSocket.handlePayload (C:\Users\leaf\Desktop\skeldjs\node_modules\@skeldjs\dtls\dist\lib\DtlsSocket.js:247:22)
    at DtlsSocket.handleRecv (C:\Users\leaf\Desktop\skeldjs\node_modules\@skeldjs\dtls\dist\lib\DtlsSocket.js:215:18)
    at Socket.<anonymous> (C:\Users\leaf\Desktop\skeldjs\node_modules\@skeldjs\dtls\dist\lib\DtlsSocket.js:67:22) {
  reason: 11
}

Node.js v17.3.0
```
i'm not sure why this happens as the code I am using is very similar to the code [here](https://skeld.js.org/pages/Getting%20Started/Creating%20a%20Client.html)

**Comment by edqx** [comment]
Hi, thanks for bringing this up.

New update looks like it broke a few things, I'll get it updated to the latest version for you. All I know currently is that the `deploymentId` variable should now read `"503cd077a7804777aee5a6eeb5cfe62d"`, but that won't completely fix it yet.
